language: android
sudo: false

jdk:
    - oraclejdk7

android:
  components:
     - platform-tools
     - tools
     - build-tools-23.0.0
     - android-23
     - extra
     - extra-google-google_play_services
     - extra-google-m2repository
     - extra-android-m2repository
     - addon-google_apis-google-19
     - sys-img-armeabi-v7a-android-22

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
 
script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request? $TRAVIS_PULL_REQUEST"
    - echo "Travis tag $TRAVIS_TAG"
    - gradle assembleRelease
    - android list target
    - ./gradlew connectedAndroidTest